name: recipe_flavored_markdown
version: 1.0.0
description: >
  Recipe-flavored markdown: make recipes easy to create and maintain!
repository: https://github.com/definitelyokay/recipe_flavored_markdown
issue_tracker: https://github.com/definitelyokay/recipe_flavored_markdown/issues
homepage: https://github.com/definitelyokay/recipe_flavored_markdown

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  markdown: ^4.0.1

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
